import * as WordUtils from './WordUtils';
import * as WordleDict from '../data/dictionaries/Wordle'
import { english3 } from '../data/dictionaries/English'


test('WordUtils.wordle properly reduces wordlist', () => {
  const allWords = WordleDict.wordleAll();
  let words;
  
  words = WordUtils.wordle(allWords, 'l-a-t-e-r?_g-i-r?l-y=_d-r?o?l-l-');
  expect(words.length).toEqual(1);
  expect(words[0]).toEqual("rocky");
  words = WordUtils.wordle(allWords, 'l-a?t-e-r-_g-i?r-l-y-_d-r-o-l-l-_r-o-c-k-y-_q-u-a?s=i?_s?w-a?m?i?_s?p-i=c-e-');
  expect(words.length).toEqual(1);
  expect(words[0]).toEqual("amiss");
  words = WordUtils.wordle(allWords, 'l?a-t-e-r?_g-i-r?l=y-');
  expect(words.length).toEqual(1);
  expect(words[0]).toEqual("droll");
  words = WordUtils.wordle(allWords, 'l-a-t?e?r-_e?x-i=s=t=');
  expect(words.length).toEqual(1);
  expect(words[0]).toEqual("heist");
  words = WordUtils.wordle(allWords, 'r-a-i-s/e-_s=n/o=u-t-');
  expect(words.length).toEqual(3);
  expect(words).toEqual(["shown", "spoon", "swoon"]);
  words = WordUtils.wordle(allWords, 'a/l/t=e=r=');
  expect(words.length).toEqual(1);
  expect(words[0]).toEqual("later");
  words = WordUtils.wordle(allWords, 'c-r-a-n-e/_s-l-e/e-t/');
  expect(words.length).toEqual(11);
  expect(words).toContain("depth");
  words = WordUtils.wordle(allWords, 's/l-e-e=t-');
  expect(words.length).toEqual(10);
  expect(words).toContain("askew");
  expect(words).toContain("riser");
})

test('WordUtils.palendroms finds palendrom pairs properly in worlde dictionary', () => {
  const words = WordleDict.wordlePicks();
  let palendroms = WordUtils.palendroms(words);
  const expected =  {
    civic: 'civic',
    kayak: 'kayak',
    lager: 'regal',
    leper: 'repel',
    level: 'level',
    lever: 'revel',
    madam: 'madam',
    minim: 'minim',
    radar: 'radar',
    rebut: 'tuber',
    refer: 'refer',
    remit: 'timer',
    rotor: 'rotor',
    tenet: 'tenet',
  };
  expect(palendroms).toEqual(expected);
})

test('WordUtils.palendroms finds palendroms properly in worlde dictionary', () => {
  const words = WordleDict.wordleAll();
  let palendroms = WordUtils.filterPalendroms(words);
  const expected =  [
    "alula",
    "anana",
    "ayaya",
    "civic",
    "deked",
    "deled",
    "dered",
    "dewed",
    "kaiak",
    "kayak",
    "lahal",
    "laval",
    "lemel",
    "level",
    "madam",
    "malam",
    "minim",
    "qajaq",
    "radar",
    "refer",
    "rotor",
    "sagas",
    "samas",
    "sedes",
    "seles",
    "semes",
    "senes",
    "seres",
    "sexes",
    "shahs",
    "simis",
    "siris",
    "solos",
    "stats",
    "stets",
    "stots",
    "sulus",
    "susus",
    "tenet",
    "torot",
   ];
  expect(palendroms).toEqual(expected);
})

test('WordUtils.rotagrams finds rotagrams properly in worlde dictionary', () => {
  const words = WordleDict.wordlePicks();
  let palendroms = WordUtils.rotagrams(words);
  const expected = {
      "alloy": ["loyal"],"anger": ["range"],"angle": ["glean"],"arson": ["sonar"],"bowel": ["elbow"],"earth": ["heart"],"easel": ["lease"],"ether": ["there"],"ethos": ["those"],"ought": ["tough"],"outer": ["route"],"setup": ["upset"],"sever": ["verse"]
    };
  expect(palendroms).toEqual(expected);
})

test('WordUtils.unique finds words with all unique letters properly', () => {
  let words = WordleDict.wordlePicks();
  let uniqueLetterWords = WordUtils.unique(words);
  let expected = [ 
    "abhor", "abide", "abled", "abode", "abort", "about", "above", "abuse", "acorn", "acrid", "actor", "acute", "adept", "admin", "admit", "adobe", "adopt", "adore", "adorn", "adult", "afire", "afoul", "after", "agent", "agile", "aglow", "agony", "aider", "aisle", "album", "alert", "alien", "align", "alike", "alive", "aloft", "alone", "along", "aloud", "alter", "amber", "amble", "amend", "amity", "among", "ample", "amply", "amuse", "angel", "anger", "angle", "angry", "angst", "anime", "ankle", "anode", "antic", "anvil", "aphid", "aping", "apron", "aptly", "argue", "arise", "arose", "arson", "artsy", "ascot", "ashen", "aside", "askew", "atone", "audio", "audit", "aunty", "avert", "avoid", "awful", "awoke", "axiom", "axion", "azure", "bacon", "badge", "badly", "bagel", "baker", "baler", "balmy", "banjo", "barge", "baron", "basic", "basil", "basin", "baste", "batch", "bathe", "baton", "bawdy", "bayou", "beach", "beady", "beard", "beast", "befit", "began", "begat", "begin", "begun", "being", "belch", "below", "bench", "berth", "bicep", "bigot", "bilge", "binge", "bingo", "biome", "birch", "birth", "bison", "black", "blade", "blame", "bland", "blank", "blare", "blast", "blaze", "bleak", "bleat", "blend", "blimp", "blind", "blink", "blitz", "bloat", "block", "bloke", "blond", "blown", "bluer", "blunt", "blurt", "blush", "board", "boast", "boney", "bonus", "borax", "borne", "botch", "bough", "boule", "bound", "bowel", "boxer", "brace", "braid", "brain", "brake", "brand", "brash", "brave", "bravo", "brawl", "brawn", "bread", "break", "brick", "bride", "brief", "brine", "bring", "brink", "briny", "brisk", "broad", "broil", "broke", "broth", "brown", "brunt", "brush", "brute", "budge", "bugle", "build", "built", "bulge", "bulky", "bunch", "burly", "burnt", "burst", "bused", "bushy", "butch", "buxom", "buyer", "bylaw", "cabin", "cable", "cadet", "cagey", "cairn", "camel", "cameo", "candy", "canoe", "caper", "caput", "cargo", "carol", "carve", "caste", "cater", "caulk", "cause", "cavil", "cedar", "chafe", "chain", "chair", "chalk", "champ", "chant", "chaos", "chard", "charm", "chart", "chase", "chasm", "cheap", "cheat", "chest", "chide", "chief", "child", "chime", "china", "chirp", "choir", "choke", "chord", "chore", "chose", "chump", "chunk", "churn", "chute", "cider", "cigar", "claim", "clamp", "clang", "clank", "clash", "clasp", "clean", "clear", "cleat", "cleft", "clerk", "climb", "cling", "clink", "cloak", "clone", "close", "cloth", "cloud", "clout", "clove", "clown", "clued", "clump", "clung", "coast", "cobra", "comet", "comfy", "copse", "coral", "corny", "cough", "could", "count", "coupe", "court", "coven", "cover", "covet", "covey", "cower", "craft", "cramp", "crane", "crank", "crash", "crate", "crave", "crawl", "craze", "crazy", "creak", "cream", "credo", "crept", "crest", "cried", "crime", "crimp", "crisp", "croak", "crone", "crony", "croup", "crowd", "crown", "crude", "cruel", "crumb", "crump", "crush", "crust", "crypt", "cumin", "curio", "curly", "curse", "curve", "curvy", "cutie", "cyber", "daily", "dairy", "daisy", "dance", "datum", "daunt", "dealt", "death", "debar", "debit", "debug", "debut", "decal", "decay", "decor", "decoy", "decry", "deign", "deity", "delay", "delta", "demon", "demur", "denim", "depot", "depth", "derby", "detox", "devil", "diary", "dicey", "dimly", "diner", "dingo", "dingy", "dirge", "dirty", "disco", "ditch", "diver", "dogma", "doing", "donut", "dopey", "doubt", "dough", "dowel", "downy", "dowry", "dozen", "draft", "drain", "drake", "drank", "drape", "drawl", "drawn", "dream", "drift", "drink", "drive", "droit", "drone", "drove", "drown", "drunk", "duchy", "dumpy", "dunce", "dusky", "dusty", "dutch", "duvet", "dwarf", "dwelt", "dying", "early", "earth", "ebony", "eclat", "edict", "edify", "eight", "eking", "elbow", "elfin", "email", "empty", "enact", "endow", "enjoy", "entry", "envoy", "epoch", "epoxy", "equal", "equip", "erupt", "ethic", "ethos", "evict", "exact", "exalt", "exist", "extol", "extra", "exult", "eying", "fable", "facet", "faint", "fairy", "faith", "false", "fancy", "farce", "fault", "favor", "feast", "fecal", "feign", "felon", "femur", "feral", "fetal", "fetch", "fetid", "fetus", "fiber", "fibre", "ficus", "field", "fiend", "fiery", "fight", "filer", "filet", "filmy", "filth", "final", "finch", "finer", "first", "fishy", "fixer", "fjord", "flack", "flair", "flake", "flaky", "flame", "flank", "flare", "flash", "flask", "fleck", "flesh", "flick", "flier", "fling", "flint", "flirt", "float", "flock", "flora", "flour", "flout", "flown", "fluid", "fluke", "flume", "flung", "flunk", "flush", "flute", "flyer", "foamy", "focal", "focus", "foist", "foray", "force", "forge", "forte", "forth", "forty", "forum", "found", "foyer", "frail", "frame", "frank", "fraud", "freak", "fresh", "fried", "frisk", "fritz", "frock", "frond", "front", "frost", "froth", "frown", "froze", "fruit", "fudge", "fungi", "funky", "gaily", "gamer", "gamut", "gaudy", "gaunt", "gauze", "gavel", "gawky", "gayer", "gazer", "gecko", "ghost", "ghoul", "giant", "gipsy", "girly", "girth", "given", "giver", "glade", "gland", "glare", "glaze", "gleam", "glean", "glide", "glint", "gloat", "globe", "glory", "glove", "glyph", "gnash", "gnome", "godly", "golem", "gonad", "goner", "gourd", "grace", "grade", "graft", "grail", "grain", "grand", "grant", "grape", "graph", "grasp", "grate", "grave", "gravy", "graze", "great", "grief", "grime", "grimy", "grind", "gripe", "groan", "groin", "grope", "group", "grout", "grove", "growl", "grown", "gruel", "grunt", "guard", "guest", "guide", "guild", "guile", "guilt", "guise", "gulch", "gumbo", "gusto", "gusty", "habit", "hairy", "halve", "handy", "hardy", "harem", "harpy", "haste", "hasty", "hater", "haunt", "haute", "haven", "havoc", "hazel", "heady", "heard", "heart", "heavy", "hefty", "heist", "helix", "heron", "hinge", "hoard", "hoist", "homer", "honey", "horde", "horny", "horse", "hotel", "hotly", "hound", "house", "hovel", "hover", "howdy", "human", "humid", "humor", "hunky", "husky", "hydro", "hyena", "hymen", "hyper", "ideal", "idler", "image", "imbue", "impel", "imply", "inbox", "incur", "index", "inept", "inert", "infer", "ingot", "inlay", "inlet", "input", "inter", "intro", "irate", "irony", "islet", "itchy", "ivory", "jaunt", "jerky", "joint", "joist", "joker", "joust", "judge", "juice", "juicy", "jumbo", "jumpy", "junta", "junto", "knave", "knead", "knelt", "knife", "labor", "laden", "lager", "lance", "lanky", "lapse", "large", "latch", "later", "lathe", "laugh", "layer", "leach", "leafy", "leaky", "leant", "leapt", "learn", "leash", "least", "lefty", "lemon", "lemur", "light", "liken", "limbo", "liner", "lingo", "lithe", "liver", "loamy", "loath", "locus", "lodge", "lofty", "logic", "login", "loser", "louse", "lousy", "lover", "lower", "lucid", "lucky", "lumen", "lumpy", "lunar", "lunch", "lunge", "lurch", "lurid", "lusty", "lying", "lymph", "lynch", "lyric", "macho", "macro", "madly", "magic", "maize", "major", "maker", "mange", "mango", "mangy", "manic", "manly", "manor", "maple", "march", "marsh", "mason", "match", "matey", "mauve", "maybe", "mayor", "mealy", "meant", "meaty", "medal", "media", "medic", "melon", "mercy", "merit", "metal", "metro", "micro", "midge", "midst", "might", "milky", "mince", "miner", "minor", "minty", "minus", "mirth", "miser", "mocha", "modal", "model", "mogul", "moist", "molar", "moldy", "money", "month", "moral", "morph", "motel", "motif", "moult", "mound", "mount", "mourn", "mouse", "mouth", "mover", "movie", "mower", "mucky", "mulch", "munch", "mural", "murky", "mushy", "music", "musky", "musty", "nadir", "naive", "nasty", "navel", "neigh", "nerdy", "newly", "nicer", "niche", "night", "noble", "nobly", "noise", "noisy", "nomad", "north", "nosey", "notch", "novel", "nudge", "nurse", "nymph", "oaken", "ocean", "octal", "often", "olden", "older", "olive", "ombre", "omega", "onset", "opera", "opine", "opium", "optic", "orbit", "organ", "other", "ought", "ounce", "outer", "ovary", "ovate", "overt", "ovine", "owing", "owner", "oxide", "paint", "paler", "palsy", "panel", "panic", "pansy", "parse", "party", "paste", "pasty", "patch", "patio", "patsy", "pause", "payer", "peach", "pearl", "pecan", "pedal", "penal", "perch", "peril", "perky", "pesky", "pesto", "petal", "phase", "phone", "phony", "piano", "picky", "piety", "pilot", "pinch", "piney", "pinky", "pinto", "pique", "pitch", "pithy", "pivot", "pixel", "place", "plaid", "plain", "plait", "plane", "plank", "plant", "plate", "plead", "pleat", "plied", "plier", "pluck", "plumb", "plume", "plunk", "plush", "poesy", "point", "poise", "poker", "polar", "polka", "porch", "poser", "posit", "pouch", "pound", "pouty", "power", "prank", "prawn", "price", "prick", "pride", "pried", "prime", "primo", "print", "prism", "privy", "prize", "probe", "prone", "prong", "prose", "proud", "prove", "prowl", "proxy", "prude", "prune", "psalm", "pubic", "pudgy", "pulse", "punch", "purge", "purse", "pushy", "quack", "quail", "quake", "qualm", "quark", "quart", "quash", "quasi", "query", "quest", "quick", "quiet", "quilt", "quirk", "quite", "quota", "quote", "quoth", "rabid", "radio", "rainy", "raise", "ralph", "ramen", "ranch", "randy", "range", "rapid", "raspy", "ratio", "raven", "rayon", "reach", "react", "ready", "realm", "rebus", "rebut", "recap", "recut", "refit", "regal", "rehab", "reign", "relax", "relay", "relic", "remit", "renal", "repay", "reply", "resin", "retch", "rhino", "rhyme", "ridge", "rifle", "right", "rinse", "ripen", "risen", "risky", "rival", "rivet", "roach", "roast", "robin", "rocky", "rogue", "rouge", "rough", "round", "rouse", "route", "rowdy", "royal", "rugby", "rumba", "rusty", "sadly", "safer", "saint", "salon", "salty", "salve", "salvo", "sandy", "saner", "satin", "satyr", "sauce", "saucy", "saute", "savor", "savoy", "scald", "scale", "scalp", "scaly", "scamp", "scant", "scare", "scarf", "scary", "scent", "scion", "scold", "scone", "scope", "score", "scorn", "scour", "scout", "scowl", "scram", "scrap", "screw", "scrub", "scrum", "scuba", "sedan", "sepia", "serif", "serum", "setup", "shack", "shade", "shady", "shaft", "shake", "shaky", "shale", "shalt", "shame", "shank", "shape", "shard", "share", "shark", "sharp", "shave", "shawl", "shear", "sheik", "shelf", "shied", "shift", "shine", "shiny", "shire", "shirk", "shirt", "shoal", "shock", "shone", "shore", "shorn", "short", "shout", "shove", "shown", "showy", "shrew", "shrub", "shrug", "shuck", "shunt", "sight", "sigma", "silky", "since", "sinew", "singe", "siren", "sixth", "sixty", "skate", "skier", "skimp", "skirt", "slack", "slain", "slang", "slant", "slate", "slave", "slept", "slice", "slick", "slide", "slime", "slimy", "sling", "slink", "slope", "sloth", "slump", "slung", "slunk", "slurp", "smack", "smart", "smear", "smelt", "smile", "smirk", "smite", "smith", "smock", "smoke", "smoky", "smote", "snack", "snail", "snake", "snaky", "snare", "snarl", "sneak", "snide", "snipe", "snore", "snort", "snout", "snowy", "snuck", "soapy", "sober", "solar", "solid", "solve", "sonar", "sonic", "sound", "south", "sower", "space", "spade", "spank", "spare", "spark", "spawn", "speak", "spear", "speck", "spelt", "spend", "spent", "sperm", "spice", "spicy", "spied", "spiel", "spike", "spiky", "spilt", "spine", "spiny", "spire", "spite", "splat", "split", "spoil", "spoke", "spore", "sport", "spout", "spray", "sprig", "spunk", "spurn", "spurt", "squad", "squat", "squib", "stack", "stage", "staid", "stain", "stair", "stake", "stale", "stalk", "stamp", "stand", "stank", "stare", "stark", "stave", "stead", "steak", "steal", "steam", "stein", "stern", "stick", "sting", "stink", "stock", "stoic", "stoke", "stole", "stomp", "stone", "stony", "store", "stork", "storm", "story", "stove", "strap", "straw", "stray", "strip", "stuck", "study", "stump", "stung", "stunk", "style", "suave", "sugar", "suing", "suite", "sulky", "sumac", "super", "surge", "surly", "swami", "swamp", "swarm", "swath", "swear", "sweat", "swept", "swift", "swine", "swing", "swirl", "sword", "swore", "sworn", "swung", "synod", "syrup", "table", "tacky", "taken", "taker", "talon", "tamer", "tango", "tangy", "taper", "tapir", "tardy", "tawny", "teach", "teary", "tempo", "tenor", "tepid", "thank", "their", "thick", "thief", "thing", "think", "third", "thong", "thorn", "those", "threw", "throb", "throw", "thrum", "thumb", "thump", "thyme", "tidal", "tiger", "tilde", "timer", "tipsy", "today", "token", "tonal", "tonga", "tonic", "topaz", "topic", "torch", "torus", "touch", "tough", "towel", "tower", "toxic", "toxin", "trace", "track", "trade", "trail", "train", "tramp", "trash", "trawl", "tread", "trend", "triad", "trial", "tribe", "trice", "trick", "tried", "tripe", "trope", "trove", "truce", "truck", "truly", "trump", "trunk", "tubal", "tuber", "tulip", "tumor", "tunic", "turbo", "twang", "tweak", "twice", "twine", "twirl", "tying", "ulcer", "ultra", "umbra", "uncle", "under", "unfed", "unfit", "unify", "unite", "unity", "unlit", "unmet", "unset", "untie", "until", "unwed", "unzip", "upset", "urban", "urine", "usage", "usher", "using", "utile", "vague", "valet", "valid", "valor", "value", "vapid", "vapor", "vault", "vaunt", "vegan", "venom", "verso", "vicar", "video", "vigor", "vinyl", "viola", "viper", "viral", "virus", "visor", "vista", "vital", "vixen", "vocal", "vodka", "vogue", "voice", "voila", "vomit", "voter", "vouch", "vowel", "vying", "wacky", "wafer", "wager", "wagon", "waist", "waive", "waltz", "warty", "waste", "watch", "water", "waver", "waxen", "weary", "weigh", "weird", "welch", "welsh", "wench", "whack", "whale", "wharf", "wheat", "whelp", "while", "whine", "whiny", "whirl", "whisk", "white", "whole", "whose", "widen", "wider", "width", "wield", "wight", "wimpy", "wince", "winch", "windy", "wiser", "wispy", "witch", "woken", "woman", "women", "wordy", "world", "worse", "worst", "worth", "would", "wound", "woven", "wrack", "wrath", "wreak", "wreck", "wrest", "wring", "wrist", "write", "wrong", "wrote", "wrung", "yacht", "yearn", "yeast", "yield", "young", "youth", "zebra", "zesty", "zonal"
  ];
  expect(uniqueLetterWords).toEqual(expected);
  words = [
    "a", "aa", "ab", "abc", "aaa", "abb", "abcdefghijklmnopqrstuvwxyz", "abcdefghijklmnopqrstuvwxyzz", "aabcdefghijklmnopqrstuvwxyz", "abcdefghijklmmnopqrstuvwxyz"
  ];
  uniqueLetterWords = WordUtils.unique(words);
  expected = ["a", "ab", "abc", "abcdefghijklmnopqrstuvwxyz"];
  expect(uniqueLetterWords).toEqual(expected);
})

test('WordUtils.matches finds words that match regex string properly', () => {
  let words = WordleDict.wordlePicks();
  let matchedWords = WordUtils.matches(words, "[^a^e^i^o^u]{5}");
  let expected = [ 
    "crypt", "dryly", "glyph", "gypsy", "lymph", "lynch", "myrrh", "nymph", "pygmy", "shyly", "slyly", "tryst", "wryly", 
  ];
  expect(matchedWords).toEqual(expected);
  words = [
    "a", "aa", "ab", "abc", "aaa", "abb", "xyz", "abcdefghijklmnopqrstuvwxyz", "abcdefghijklmnopqrstuvwxyzz", "aabcdefghijklmnopqrstuvwxyz", "abcdefghijklmmnopqrstuvwxyz"
  ];
  matchedWords = WordUtils.matches(words, "xyz$");
  expected = ["xyz", "abcdefghijklmnopqrstuvwxyz", "aabcdefghijklmnopqrstuvwxyz", "abcdefghijklmmnopqrstuvwxyz"];
  expect(matchedWords).toEqual(expected);
})

test('WordUtils.getWordleClues gets clues properly', () => {
  let expected = 'enene';
  let clues = WordUtils.getWordleClues("abcde", "axcxe");
  expect(clues).toEqual(expected);
  expected = 'epepe';
  clues = WordUtils.getWordleClues("abcde", "adcbe");
  expect(clues).toEqual(expected);
  expected = 'nnnnn';
  clues = WordUtils.getWordleClues("abcde", "vwxyz");
  expect(clues).toEqual(expected);
  expected = 'ppppp';
  clues = WordUtils.getWordleClues("abcde", "bcdea");
  expect(clues).toEqual(expected);
  expected = 'ennnn';
  clues = WordUtils.getWordleClues("abcde", "aaaaa");
  expect(clues).toEqual(expected);
  expected = 'pnnnn';
  clues = WordUtils.getWordleClues("eaaaa", "beeee");
  expect(clues).toEqual(expected);
  expected = 'npnnn';
  clues = WordUtils.getWordleClues("abbbb", "beeee");
  expect(clues).toEqual(expected);
  expected = 'pnnnp';
  clues = WordUtils.getWordleClues("abbba", "eaeae");
  expect(clues).toEqual(expected);
  expected = 'npnpn';
  clues = WordUtils.getWordleClues("eaeae", "abbba");
  expect(clues).toEqual(expected);
  expected = 'epppp';
  clues = WordUtils.getWordleClues("eaeae", "eeaea");
  expect(clues).toEqual(expected);
})

test('WordUtils.getWordlePartitions works properly', () => {
  let words = ["abcde", 
  "eaaaa", 
  "abbbb", 
  "abbba", 
  "eaeae", 
  "eaeae"];
  let picks = ["axcxe"
  , "adcbe"
  , "vwxyz"
  , "bcdea"
  , "aaaaa"
  , "beeee"
  , "eaeae"
  , "abbba"
  , "eeaea"];
  let expected = {
    abbba: {
        eeeee: [
            "abbba",
            ],
        ennen: [
            "adcbe",
            ],
        ennne: [
            "aaaaa",
            ],
        ennnn: [
            "axcxe",
            ],
        nnnnn: [
            "vwxyz",
            ],
        npnne: [
            "bcdea",
            ],
        npnnn: [
            "beeee",
            ],
        pnnne: [
            "eeaea",
            ],
        pnnnp: [
            "eaeae",
            ],
        },
    abbbb: {
        eeeen: [
            "abbba",
            ],
        ennen: [
            "adcbe",
            ],
        ennnn: [
            "axcxe",
            "aaaaa",
            ],
        nnnnn: [
            "vwxyz",
            ],
        npnnn: [
            "beeee",
            ],
        pnnnn: [
            "eaeae",
            "eeaea",
            ],
        ppnnn: [
            "bcdea",
            ],
        },
    abcde: {
        eennn: [
            "abbba",
            ],
        enene: [
            "axcxe",
            ],
        ennnn: [
            "aaaaa",
            ],
        epepe: [
            "adcbe",
            ],
        nnnnn: [
            "vwxyz",
            ],
        npnne: [
            "beeee",
            ],
        pnnne: [
            "eaeae",
            ],
        pnnnp: [
            "eeaea",
            ],
        ppppp: [
            "bcdea",
            ],
        },
    eaaaa: {
        eenen: [
            "eaeae",
            ],
        enene: [
            "eeaea",
            ],
        neeee: [
            "aaaaa",
            ],
        nnnnn: [
            "vwxyz",
            ],
        npnne: [
            "abbba",
            ],
        pnnne: [
            "bcdea",
            ],
        pnnnn: [
            "beeee",
            ],
        ppnnn: [
            "axcxe",
            "adcbe",
            ],
        },
    eaeae: {
        eeeee: [
            "eaeae",
            ],
        epppp: [
            "eeaea",
            ],
        nenen: [
            "aaaaa",
            ],
        nnnnn: [
            "vwxyz",
            ],
        npnne: [
            "axcxe",
            "adcbe",
            ],
        npnpn: [
            "abbba",
            ],
        pnene: [
            "beeee",
            ],
        ppnnn: [
            "bcdea",
            ],
        },
};
  let partitions = WordUtils.getWordlePartitions(words, picks);
  expect(partitions).toEqual(expected);
  picks = WordleDict.wordlePicks();
  words = ["crate"];
  expected = {
    "crate": {
      "eeeee": [
        "crate",
      ],
      "eeene": [
        "crane",
        "crave",
        "craze",
      ],
      "eeenn": [
        "crack",
        "cramp",
        "crank",
        "crash",
        "crass",
        "crawl",
        "crazy",
      ],
      "eeepn": [
        "craft",
      ],
      "eenne": [
        "creme",
        "crepe",
        "crime",
        "crone",
        "crude",
      ],
      "eennn": [
        "crick",
        "crimp",
        "crisp",
        "crock",
        "crony",
        "crook",
        "cross",
        "croup",
        "crowd",
        "crown",
        "crumb",
        "crump",
        "crush",
      ],
      "eennp": [
        "credo",
        "creed",
        "creek",
        "creep",
        "cress",
        "cried",
        "crier",
        "cruel",
      ],
      "eenpn": [
        "crust",
        "crypt",
      ],
      "eenpp": [
        "crept",
        "crest",
      ],
      "eepnn": [
        "croak",
      ],
      "eepnp": [
        "creak",
        "cream",
      ],
      "enene": [
        "cease",
        "chafe",
        "chase",
      ],
      "enenn": [
        "chaff",
        "chain",
        "chalk",
        "champ",
        "chaos",
        "chasm",
        "clack",
        "claim",
        "clamp",
        "clang",
        "clank",
        "clash",
        "clasp",
        "class",
        "coach",
      ],
      "enepn": [
        "chant",
        "coast",
      ],
      "ennee": [
        "chute",
      ],
      "ennen": [
        "cloth",
      ],
      "ennne": [
        "chide",
        "chime",
        "choke",
        "chose",
        "clone",
        "close",
        "clove",
        "copse",
        "coupe",
        "cycle",
      ],
      "ennnn": [
        "chick",
        "child",
        "chili",
        "chill",
        "chock",
        "chuck",
        "chump",
        "chunk",
        "cinch",
        "civic",
        "civil",
        "click",
        "cliff",
        "climb",
        "cling",
        "clink",
        "clock",
        "cloud",
        "clown",
        "cluck",
        "clump",
        "clung",
        "colon",
        "comfy",
        "comic",
        "conch",
        "condo",
        "conic",
        "couch",
        "cough",
        "could",
        "coyly",
        "cubic",
        "cumin",
        "cynic",
      ],
      "ennnp": [
        "cello",
        "check",
        "cheek",
        "chess",
        "chief",
        "clued",
        "coven",
        "covey",
      ],
      "ennpe": [
        "cutie",
      ],
      "ennpn": [
        "clout",
        "count",
      ],
      "ennpp": [
        "chest",
        "cleft",
        "comet",
        "covet",
      ],
      "enpee": [
        "caste",
      ],
      "enpen": [
        "cacti",
        "catty",
      ],
      "enpne": [
        "cable",
        "cache",
        "canoe",
        "cause",
      ],
      "enpnn": [
        "cabal",
        "cabby",
        "cabin",
        "cacao",
        "caddy",
        "canal",
        "candy",
        "canny",
        "canon",
        "caulk",
        "cavil",
        "china",
        "cloak",
        "cocoa",
        "comma",
      ],
      "enpnp": [
        "cagey",
        "camel",
        "cameo",
        "cheap",
        "clean",
      ],
      "enppn": [
        "caput",
        "catch",
      ],
      "enppp": [
        "cadet",
        "cheat",
        "cleat",
      ],
      "epenn": [
        "chair",
        "chard",
        "charm",
      ],
      "epepn": [
        "chart",
      ],
      "epnne": [
        "chore",
        "curse",
        "curve",
      ],
      "epnnn": [
        "chirp",
        "choir",
        "chord",
        "churn",
        "color",
        "corny",
        "curio",
        "curly",
        "curry",
        "curvy",
      ],
      "epnnp": [
        "cheer",
        "cider",
        "clerk",
        "corer",
        "cover",
        "cower",
        "cyber",
      ],
      "epnpn": [
        "court",
      ],
      "eppne": [
        "carve",
      ],
      "eppnn": [
        "cairn",
        "cargo",
        "carol",
        "carry",
        "cigar",
        "circa",
        "cobra",
        "coral",
      ],
      "eppnp": [
        "caper",
        "cedar",
        "clear",
      ],
      "epppn": [
        "carat",
      ],
      "epppp": [
        "cater",
      ],
      "neeee": [
        "grate",
        "irate",
      ],
      "neeen": [
        "wrath",
      ],
      "neene": [
        "brake",
        "brave",
        "drake",
        "drape",
        "erase",
        "frame",
        "grade",
        "grape",
        "grave",
        "graze",
      ],
      "neenn": [
        "braid",
        "brain",
        "brand",
        "brash",
        "brass",
        "bravo",
        "brawl",
        "brawn",
        "drain",
        "drama",
        "drank",
        "drawl",
        "drawn",
        "frail",
        "frank",
        "fraud",
        "grail",
        "grain",
        "grand",
        "graph",
        "grasp",
        "grass",
        "gravy",
        "prank",
        "prawn",
      ],
      "neepe": [
        "trade",
      ],
      "neepn": [
        "draft",
        "graft",
        "grant",
        "trail",
        "train",
        "trait",
        "tramp",
        "trash",
        "trawl",
      ],
      "nenee": [
        "brute",
        "trite",
        "write",
        "wrote",
      ],
      "nenen": [
        "broth",
        "fritz",
        "froth",
        "truth",
      ],
      "nenne": [
        "bribe",
        "bride",
        "brine",
        "broke",
        "drive",
        "drone",
        "drove",
        "erode",
        "froze",
        "grime",
        "gripe",
        "grope",
        "grove",
        "pride",
        "prime",
        "prize",
        "probe",
        "prone",
        "prose",
        "prove",
        "prude",
        "prune",
        "urine",
      ],
      "nennn": [
        "bring",
        "brink",
        "briny",
        "brisk",
        "broil",
        "brood",
        "brook",
        "broom",
        "brown",
        "brush",
        "drill",
        "drink",
        "droll",
        "drool",
        "droop",
        "dross",
        "drown",
        "druid",
        "drunk",
        "dryly",
        "frill",
        "frisk",
        "frond",
        "frown",
        "grill",
        "grimy",
        "grind",
        "groin",
        "groom",
        "gross",
        "group",
        "growl",
        "grown",
        "gruff",
        "irony",
        "krill",
        "primo",
        "prior",
        "prism",
        "privy",
        "prong",
        "proof",
        "proud",
        "prowl",
        "proxy",
        "wring",
        "wrong",
        "wrung",
        "wryly",
      ],
      "nennp": [
        "breed",
        "brief",
        "dress",
        "dried",
        "drier",
        "dryer",
        "error",
        "freed",
        "freer",
        "fresh",
        "fried",
        "greed",
        "green",
        "grief",
        "gruel",
        "order",
        "preen",
        "press",
        "pried",
      ],
      "nenpe": [
        "tribe",
        "tripe",
        "trope",
        "trove",
      ],
      "nenpn": [
        "brunt",
        "drift",
        "droit",
        "front",
        "frost",
        "fruit",
        "grout",
        "grunt",
        "orbit",
        "print",
        "troll",
        "troop",
        "trout",
        "truly",
        "trump",
        "trunk",
        "truss",
        "trust",
        "tryst",
        "wrist",
      ],
      "nenpp": [
        "erupt",
        "greet",
        "trend",
        "tried",
        "truer",
        "wrest",
      ],
      "nepne": [
        "argue",
        "arise",
        "arose",
      ],
      "nepnn": [
        "arbor",
        "ardor",
        "armor",
        "aroma",
        "array",
        "arrow",
        "arson",
        "briar",
        "broad",
        "friar",
        "groan",
        "organ",
        "urban",
      ],
      "nepnp": [
        "arena",
        "bread",
        "break",
        "dread",
        "dream",
        "freak",
        "wreak",
      ],
      "neppn": [
        "artsy",
        "triad",
        "trial",
      ],
      "neppp": [
        "great",
        "tread",
        "treat",
      ],
      "nneee": [
        "abate",
        "agate",
        "elate",
        "ovate",
        "plate",
        "skate",
        "slate",
        "state",
      ],
      "nneen": [
        "loath",
        "swath",
      ],
      "nneep": [
        "death",
        "heath",
        "meaty",
      ],
      "nnene": [
        "abase",
        "adage",
        "agape",
        "amaze",
        "awake",
        "blade",
        "blame",
        "blaze",
        "evade",
        "flake",
        "flame",
        "glade",
        "glaze",
        "heave",
        "image",
        "inane",
        "knave",
        "lease",
        "leave",
        "phase",
        "plane",
        "quake",
        "shade",
        "shake",
        "shale",
        "shame",
        "shape",
        "shave",
        "slave",
        "snake",
        "spade",
        "suave",
        "usage",
        "weave",
        "whale",
      ],
      "nnenn": [
        "again",
        "amass",
        "avail",
        "awash",
        "bland",
        "blank",
        "flail",
        "flaky",
        "flank",
        "flash",
        "flask",
        "foamy",
        "gland",
        "glass",
        "gnash",
        "guava",
        "khaki",
        "koala",
        "llama",
        "loamy",
        "piano",
        "plaid",
        "plain",
        "plank",
        "plaza",
        "psalm",
        "quail",
        "qualm",
        "quash",
        "quasi",
        "shady",
        "shaky",
        "shall",
        "shank",
        "shawl",
        "slain",
        "slang",
        "slash",
        "small",
        "smash",
        "snail",
        "snaky",
        "soapy",
        "spank",
        "spasm",
        "spawn",
        "swami",
        "swamp",
        "swash",
      ],
      "nnenp": [
        "beady",
        "email",
        "heady",
        "heavy",
        "leafy",
        "leaky",
        "leash",
        "mealy",
      ],
      "nnepe": [
        "stage",
        "stake",
        "stale",
        "stave",
        "tease",
      ],
      "nnepn": [
        "adapt",
        "await",
        "blast",
        "boast",
        "giant",
        "plait",
        "plant",
        "shaft",
        "shalt",
        "slant",
        "staff",
        "staid",
        "stain",
        "stalk",
        "stall",
        "stamp",
        "stand",
        "stank",
        "stash",
        "thank",
        "toast",
        "twang",
      ],
      "nnepp": [
        "beast",
        "dealt",
        "exalt",
        "feast",
        "leant",
        "leapt",
        "least",
        "meant",
        "yeast",
      ],
      "nnnee": [
        "butte",
        "elite",
        "flute",
        "quite",
        "quote",
        "smite",
        "smote",
        "spite",
        "suite",
        "unite",
        "white",
      ],
      "nnnen": [
        "bitty",
        "blitz",
        "booth",
        "booty",
        "ditto",
        "ditty",
        "dusty",
        "fifth",
        "fifty",
        "filth",
        "gusto",
        "gusty",
        "junto",
        "kitty",
        "lofty",
        "lusty",
        "minty",
        "month",
        "motto",
        "mouth",
        "musty",
        "ninth",
        "nutty",
        "photo",
        "pinto",
        "pouty",
        "putty",
        "quoth",
        "sixth",
        "sixty",
        "sloth",
        "smith",
        "sooth",
        "sooty",
        "south",
        "tooth",
        "unity",
        "width",
        "witty",
        "youth",
      ],
      "nnnep": [
        "deity",
        "depth",
        "empty",
        "hefty",
        "jetty",
        "lefty",
        "pesto",
        "petty",
        "piety",
        "teeth",
        "tenth",
        "testy",
        "zesty",
      ],
      "nnnne": [
        "belie",
        "belle",
        "bible",
        "bilge",
        "binge",
        "biome",
        "bloke",
        "booze",
        "boule",
        "budge",
        "bugle",
        "bulge",
        "delve",
        "dense",
        "diode",
        "dodge",
        "elide",
        "elope",
        "elude",
        "ensue",
        "evoke",
        "exile",
        "femme",
        "fluke",
        "flume",
        "fudge",
        "fugue",
        "geese",
        "genie",
        "glide",
        "globe",
        "glove",
        "gnome",
        "goose",
        "gouge",
        "guide",
        "guile",
        "guise",
        "hedge",
        "hinge",
        "house",
        "imbue",
        "issue",
        "judge",
        "knife",
        "ledge",
        "liege",
        "lodge",
        "loose",
        "louse",
        "lunge",
        "melee",
        "midge",
        "moose",
        "mouse",
        "movie",
        "noble",
        "noise",
        "noose",
        "nudge",
        "obese",
        "olive",
        "opine",
        "ovine",
        "oxide",
        "ozone",
        "penne",
        "phone",
        "pique",
        "pixie",
        "plume",
        "poise",
        "posse",
        "pulse",
        "queue",
        "segue",
        "seize",
        "sense",
        "shine",
        "shone",
        "shove",
        "siege",
        "sieve",
        "singe",
        "slide",
        "slime",
        "slope",
        "smile",
        "smoke",
        "snide",
        "snipe",
        "solve",
        "spike",
        "spine",
        "spoke",
        "swine",
        "undue",
        "venue",
        "vogue",
        "wedge",
        "while",
        "whine",
        "whole",
        "whose",
      ],
      "nnnnn": [
        "biddy",
        "billy",
        "bingo",
        "bison",
        "blimp",
        "blind",
        "blink",
        "bliss",
        "blond",
        "blood",
        "bloom",
        "blown",
        "bluff",
        "blush",
        "bobby",
        "bongo",
        "bonus",
        "booby",
        "boozy",
        "bosom",
        "bossy",
        "bough",
        "bound",
        "buddy",
        "buggy",
        "build",
        "bulky",
        "bully",
        "bunny",
        "bushy",
        "buxom",
        "dilly",
        "dimly",
        "dingo",
        "dingy",
        "dizzy",
        "dodgy",
        "doing",
        "dolly",
        "dough",
        "dowdy",
        "downy",
        "dully",
        "dummy",
        "dumpy",
        "dusky",
        "dying",
        "filly",
        "filmy",
        "fishy",
        "fizzy",
        "fling",
        "flood",
        "floss",
        "flown",
        "fluff",
        "fluid",
        "flung",
        "flunk",
        "flush",
        "foggy",
        "folio",
        "folly",
        "found",
        "fully",
        "fungi",
        "funky",
        "funny",
        "fussy",
        "fuzzy",
        "ghoul",
        "giddy",
        "gipsy",
        "gloom",
        "gloss",
        "glyph",
        "godly",
        "going",
        "golly",
        "goody",
        "goofy",
        "guild",
        "gully",
        "gumbo",
        "gummy",
        "guppy",
        "gypsy",
        "hilly",
        "hippo",
        "hippy",
        "hobby",
        "holly",
        "hound",
        "howdy",
        "humid",
        "humph",
        "humus",
        "hunky",
        "husky",
        "hussy",
        "idiom",
        "idyll",
        "igloo",
        "imply",
        "inbox",
        "jiffy",
        "jolly",
        "jumbo",
        "jumpy",
        "kinky",
        "kiosk",
        "knoll",
        "known",
        "limbo",
        "lingo",
        "lipid",
        "livid",
        "lobby",
        "login",
        "loopy",
        "lousy",
        "lowly",
        "lumpy",
        "lupus",
        "lying",
        "lymph",
        "milky",
        "minim",
        "minus",
        "missy",
        "mogul",
        "moldy",
        "moody",
        "mossy",
        "mound",
        "muddy",
        "mummy",
        "mushy",
        "musky",
        "ninny",
        "nobly",
        "noisy",
        "nylon",
        "nymph",
        "oddly",
        "onion",
        "opium",
        "ovoid",
        "owing",
        "phony",
        "piggy",
        "pinky",
        "plumb",
        "plump",
        "plunk",
        "plush",
        "polyp",
        "poppy",
        "pound",
        "pudgy",
        "puffy",
        "pulpy",
        "pupil",
        "puppy",
        "pushy",
        "pygmy",
        "quill",
        "shiny",
        "shook",
        "shown",
        "showy",
        "shush",
        "shyly",
        "silky",
        "silly",
        "sissy",
        "skiff",
        "skill",
        "skimp",
        "skulk",
        "skull",
        "skunk",
        "slimy",
        "sling",
        "slink",
        "sloop",
        "slosh",
        "slump",
        "slung",
        "slunk",
        "slush",
        "slyly",
        "smoky",
        "sniff",
        "snoop",
        "snowy",
        "snuff",
        "soggy",
        "solid",
        "sound",
        "spiky",
        "spill",
        "spiny",
        "spoil",
        "spoof",
        "spook",
        "spool",
        "spoon",
        "spunk",
        "squib",
        "suing",
        "sulky",
        "sully",
        "sunny",
        "sushi",
        "swill",
        "swing",
        "swish",
        "swoon",
        "swoop",
        "swung",
        "synod",
        "undid",
        "unify",
        "union",
        "unzip",
        "using",
        "vigil",
        "vinyl",
        "vivid",
        "vying",
        "whiff",
        "whiny",
        "whisk",
        "whoop",
        "widow",
        "willy",
        "wimpy",
        "windy",
        "wispy",
        "woody",
        "wooly",
        "woozy",
        "would",
        "wound",
        "young",
      ],
      "nnnnp": [
        "beefy",
        "begin",
        "begun",
        "being",
        "belly",
        "below",
        "bevel",
        "bezel",
        "bleed",
        "bleep",
        "blend",
        "bless",
        "boney",
        "bowel",
        "bused",
        "debug",
        "deign",
        "demon",
        "denim",
        "devil",
        "dopey",
        "dowel",
        "dozen",
        "dwell",
        "ebony",
        "edify",
        "eking",
        "elbow",
        "elegy",
        "elfin",
        "embed",
        "endow",
        "enemy",
        "enjoy",
        "ennui",
        "envoy",
        "epoxy",
        "equip",
        "expel",
        "eying",
        "feign",
        "felon",
        "field",
        "fiend",
        "flesh",
        "geeky",
        "given",
        "golem",
        "gooey",
        "guess",
        "helix",
        "hello",
        "honey",
        "hovel",
        "hymen",
        "impel",
        "index",
        "jelly",
        "jewel",
        "kneed",
        "kneel",
        "leggy",
        "lemon",
        "level",
        "libel",
        "liken",
        "linen",
        "lumen",
        "melon",
        "model",
        "modem",
        "money",
        "needy",
        "neigh",
        "newly",
        "nosey",
        "novel",
        "olden",
        "penny",
        "pesky",
        "piney",
        "pixel",
        "plied",
        "poesy",
        "queen",
        "quell",
        "seedy",
        "semen",
        "seven",
        "sheen",
        "sheep",
        "sheik",
        "shelf",
        "shell",
        "shied",
        "sinew",
        "sleek",
        "sleep",
        "smell",
        "speed",
        "spell",
        "spend",
        "spied",
        "spiel",
        "sweep",
        "swell",
        "unfed",
        "unwed",
        "venom",
        "video",
        "vixen",
        "vowel",
        "weedy",
        "weigh",
        "welsh",
        "wheel",
        "whelp",
        "widen",
        "wield",
        "woken",
        "women",
        "woven",
        "yield",
      ],
      "nnnpe": [
        "etude",
        "lithe",
        "stoke",
        "stole",
        "stone",
        "stove",
        "style",
        "tense",
        "tepee",
        "theme",
        "these",
        "those",
        "thyme",
        "tilde",
        "tithe",
        "title",
        "tulle",
        "twine",
        "untie",
        "utile",
      ],
      "nnnpn": [
        "bigot",
        "blunt",
        "boost",
        "built",
        "digit",
        "donut",
        "doubt",
        "fight",
        "flint",
        "flout",
        "foist",
        "ghost",
        "glint",
        "guilt",
        "hoist",
        "hotly",
        "idiot",
        "ingot",
        "input",
        "joint",
        "joist",
        "joust",
        "light",
        "limit",
        "midst",
        "might",
        "moist",
        "motif",
        "moult",
        "mount",
        "night",
        "ought",
        "outdo",
        "outgo",
        "pilot",
        "pithy",
        "pivot",
        "point",
        "posit",
        "quilt",
        "shift",
        "shoot",
        "shout",
        "shunt",
        "sight",
        "snout",
        "spilt",
        "split",
        "spout",
        "stiff",
        "still",
        "stilt",
        "sting",
        "stink",
        "stint",
        "stomp",
        "stony",
        "stood",
        "stool",
        "stoop",
        "stout",
        "study",
        "stuff",
        "stump",
        "stung",
        "stunk",
        "stunt",
        "swift",
        "thigh",
        "thing",
        "think",
        "thong",
        "thumb",
        "thump",
        "tight",
        "timid",
        "tipsy",
        "toddy",
        "tough",
        "toxin",
        "tulip",
        "twist",
        "twixt",
        "tying",
        "unfit",
        "unlit",
        "until",
        "visit",
        "vomit",
        "wight",
      ],
      "nnnpp": [
        "befit",
        "beget",
        "beset",
        "betel",
        "debit",
        "debut",
        "depot",
        "detox",
        "duvet",
        "dwelt",
        "eight",
        "ethos",
        "event",
        "exist",
        "extol",
        "exult",
        "fetid",
        "fetus",
        "filet",
        "fleet",
        "guest",
        "heist",
        "hotel",
        "inept",
        "inlet",
        "islet",
        "knelt",
        "motel",
        "often",
        "onset",
        "quest",
        "quiet",
        "setup",
        "sheet",
        "sleet",
        "slept",
        "smelt",
        "spelt",
        "spent",
        "steed",
        "steel",
        "steep",
        "stein",
        "sweet",
        "swept",
        "teddy",
        "tempo",
        "tenet",
        "tepid",
        "theft",
        "thief",
        "token",
        "totem",
        "towel",
        "tweed",
        "tweet",
        "unmet",
        "unset",
        "upset",
      ],
      "nnpee": [
        "baste",
        "haste",
        "haute",
        "latte",
        "paste",
        "saute",
        "taste",
        "waste",
      ],
      "nnpen": [
        "amity",
        "aunty",
        "batty",
        "faith",
        "fatty",
        "hasty",
        "junta",
        "nasty",
        "pasta",
        "pasty",
        "patty",
        "quota",
        "salty",
        "tasty",
        "tatty",
        "vista",
        "waltz",
      ],
      "nnpep": [
        "delta",
        "theta",
      ],
      "nnpne": [
        "abide",
        "abode",
        "above",
        "abuse",
        "adobe",
        "agile",
        "aisle",
        "algae",
        "alike",
        "alive",
        "alone",
        "amble",
        "ample",
        "amuse",
        "angle",
        "anime",
        "ankle",
        "anode",
        "apple",
        "aside",
        "awoke",
        "badge",
        "eagle",
        "fable",
        "false",
        "gaffe",
        "gauge",
        "gauze",
        "halve",
        "ladle",
        "lapse",
        "maize",
        "mange",
        "maple",
        "masse",
        "mauve",
        "maybe",
        "naive",
        "pause",
        "payee",
        "salve",
        "vague",
        "value",
        "valve",
        "waive",
      ],
      "nnpnn": [
        "abyss",
        "admin",
        "affix",
        "afoul",
        "aging",
        "aglow",
        "agony",
        "album",
        "alibi",
        "align",
        "allay",
        "allow",
        "alloy",
        "along",
        "aloof",
        "aloud",
        "alpha",
        "amiss",
        "among",
        "amply",
        "annoy",
        "annul",
        "anvil",
        "aphid",
        "aping",
        "apply",
        "assay",
        "audio",
        "avian",
        "avoid",
        "awful",
        "axial",
        "axiom",
        "axion",
        "badly",
        "baggy",
        "balmy",
        "banal",
        "banjo",
        "basal",
        "basil",
        "basin",
        "basis",
        "bawdy",
        "bayou",
        "bylaw",
        "daddy",
        "daily",
        "daisy",
        "dally",
        "dandy",
        "dogma",
        "fanny",
        "fauna",
        "final",
        "gaily",
        "gamma",
        "gassy",
        "gaudy",
        "gawky",
        "gayly",
        "gonad",
        "handy",
        "happy",
        "human",
        "inlay",
        "jazzy",
        "kappa",
        "kayak",
        "lanky",
        "lasso",
        "laugh",
        "loyal",
        "madam",
        "madly",
        "mafia",
        "magma",
        "mambo",
        "mamma",
        "mammy",
        "manga",
        "mango",
        "mangy",
        "mania",
        "manly",
        "mason",
        "maxim",
        "modal",
        "nanny",
        "nasal",
        "naval",
        "ninja",
        "nomad",
        "offal",
        "paddy",
        "pagan",
        "palsy",
        "pansy",
        "papal",
        "pizza",
        "polka",
        "pupal",
        "sadly",
        "salad",
        "sally",
        "salon",
        "salsa",
        "salvo",
        "sandy",
        "sappy",
        "sassy",
        "sauna",
        "savoy",
        "savvy",
        "shoal",
        "sigma",
        "squad",
        "usual",
        "valid",
        "vapid",
        "villa",
        "viola",
        "vodka",
        "voila",
        "wagon",
        "woman",
        "zonal",
      ],
      "nnpnp": [
        "abbey",
        "abled",
        "ahead",
        "alien",
        "alley",
        "amend",
        "angel",
        "annex",
        "apnea",
        "ashen",
        "askew",
        "bagel",
        "began",
        "bleak",
        "delay",
        "easel",
        "enema",
        "equal",
        "essay",
        "fella",
        "gavel",
        "gleam",
        "glean",
        "haven",
        "hazel",
        "hyena",
        "ideal",
        "kebab",
        "knead",
        "label",
        "laden",
        "lapel",
        "legal",
        "medal",
        "media",
        "navel",
        "oaken",
        "omega",
        "panel",
        "pedal",
        "penal",
        "plead",
        "sedan",
        "sepia",
        "sneak",
        "speak",
        "vegan",
        "waxen",
      ],
      "nnppe": [
        "atone",
        "bathe",
        "lathe",
        "table",
      ],
      "nnppn": [
        "abbot",
        "about",
        "admit",
        "adopt",
        "adult",
        "afoot",
        "allot",
        "aloft",
        "angst",
        "aptly",
        "atoll",
        "audit",
        "baton",
        "bloat",
        "datum",
        "daunt",
        "faint",
        "fatal",
        "fault",
        "float",
        "gamut",
        "gaunt",
        "gloat",
        "habit",
        "haunt",
        "jaunt",
        "natal",
        "paint",
        "patio",
        "patsy",
        "saint",
        "satin",
        "splat",
        "squat",
        "tabby",
        "taboo",
        "taffy",
        "taint",
        "tally",
        "talon",
        "tango",
        "tangy",
        "taunt",
        "tawny",
        "tibia",
        "tidal",
        "titan",
        "today",
        "tonal",
        "tonga",
        "topaz",
        "total",
        "tubal",
        "vault",
        "vaunt",
        "vital",
        "waist",
      ],
      "nnppp": [
        "adept",
        "agent",
        "asset",
        "begat",
        "bleat",
        "eaten",
        "fetal",
        "matey",
        "metal",
        "petal",
        "pleat",
        "stead",
        "steak",
        "steal",
        "steam",
        "sweat",
        "taken",
        "tweak",
        "valet",
        "wheat",
      ],
      "npene": [
        "aware",
        "blare",
        "flare",
        "glare",
        "share",
        "snare",
        "spare",
      ],
      "npenn": [
        "alarm",
        "award",
        "board",
        "diary",
        "dwarf",
        "flair",
        "guard",
        "hoard",
        "ovary",
        "quark",
        "shard",
        "shark",
        "sharp",
        "snarl",
        "spark",
        "swarm",
        "wharf",
      ],
      "npenp": [
        "beard",
        "heard",
        "learn",
        "pearl",
        "ready",
        "realm",
        "rearm",
        "weary",
        "yearn",
      ],
      "npepe": [
        "stare",
      ],
      "npepn": [
        "apart",
        "quart",
        "roast",
        "smart",
        "stair",
        "stark",
        "start",
        "tiara",
      ],
      "npepp": [
        "heart",
        "teary",
      ],
      "npnee": [
        "forte",
        "route",
      ],
      "npnen": [
        "birth",
        "dirty",
        "forth",
        "forty",
        "girth",
        "mirth",
        "north",
        "rusty",
        "worth",
      ],
      "npnep": [
        "berth",
      ],
      "npnne": [
        "borne",
        "dirge",
        "eerie",
        "fibre",
        "forge",
        "genre",
        "gorge",
        "horde",
        "horse",
        "merge",
        "nerve",
        "nurse",
        "ombre",
        "puree",
        "purge",
        "purse",
        "reuse",
        "revue",
        "rhyme",
        "ridge",
        "rifle",
        "rinse",
        "rogue",
        "rouge",
        "rouse",
        "rupee",
        "serve",
        "shire",
        "shore",
        "snore",
        "spire",
        "spore",
        "spree",
        "surge",
        "swore",
        "verge",
        "verse",
        "verve",
        "where",
        "worse",
      ],
      "npnnn": [
        "blurb",
        "burly",
        "donor",
        "dowry",
        "fjord",
        "floor",
        "flour",
        "forgo",
        "forum",
        "furor",
        "furry",
        "girly",
        "glory",
        "gourd",
        "honor",
        "horny",
        "humor",
        "hurry",
        "hydro",
        "ivory",
        "juror",
        "lorry",
        "lurid",
        "minor",
        "moron",
        "morph",
        "mourn",
        "murky",
        "myrrh",
        "quirk",
        "rhino",
        "rigid",
        "rigor",
        "risky",
        "robin",
        "roomy",
        "rough",
        "round",
        "rowdy",
        "ruddy",
        "rugby",
        "rumor",
        "shirk",
        "shorn",
        "shrub",
        "shrug",
        "slurp",
        "smirk",
        "sorry",
        "sprig",
        "spurn",
        "surly",
        "swirl",
        "sword",
        "sworn",
        "syrup",
        "usurp",
        "vigor",
        "virus",
        "visor",
        "whirl",
        "wordy",
        "world",
        "worry",
      ],
      "npnnp": [
        "berry",
        "bluer",
        "boxer",
        "buyer",
        "defer",
        "demur",
        "derby",
        "diner",
        "diver",
        "elder",
        "ember",
        "every",
        "femur",
        "ferry",
        "fever",
        "fewer",
        "fiber",
        "fiery",
        "filer",
        "finer",
        "fixer",
        "flier",
        "flyer",
        "foyer",
        "giver",
        "goner",
        "heron",
        "homer",
        "hover",
        "hyper",
        "idler",
        "infer",
        "inner",
        "jerky",
        "joker",
        "leery",
        "lemur",
        "leper",
        "lever",
        "liner",
        "liver",
        "loser",
        "lover",
        "lower",
        "merry",
        "miner",
        "miser",
        "mover",
        "mower",
        "nerdy",
        "never",
        "newer",
        "odder",
        "offer",
        "older",
        "owner",
        "peril",
        "perky",
        "piper",
        "plier",
        "poker",
        "poser",
        "power",
        "purer",
        "queer",
        "query",
        "rebel",
        "rebus",
        "reedy",
        "refer",
        "reign",
        "renew",
        "repel",
        "reply",
        "rerun",
        "resin",
        "revel",
        "rider",
        "ripen",
        "riper",
        "risen",
        "riser",
        "river",
        "rodeo",
        "roger",
        "rover",
        "rower",
        "ruder",
        "ruler",
        "serif",
        "serum",
        "sever",
        "sewer",
        "sheer",
        "shrew",
        "siren",
        "skier",
        "sneer",
        "sober",
        "sower",
        "sperm",
        "super",
        "surer",
        "udder",
        "under",
        "upper",
        "usher",
        "verso",
        "viper",
        "weird",
        "wider",
        "wiser",
        "wooer",
      ],
      "npnpe": [
        "store",
        "terse",
        "there",
        "three",
      ],
      "npnpn": [
        "blurt",
        "burnt",
        "burst",
        "first",
        "flirt",
        "intro",
        "motor",
        "right",
        "robot",
        "roost",
        "rotor",
        "shirt",
        "short",
        "skirt",
        "snort",
        "sport",
        "spurt",
        "stork",
        "storm",
        "story",
        "strip",
        "strut",
        "third",
        "thorn",
        "throb",
        "throw",
        "thrum",
        "torso",
        "torus",
        "tumor",
        "turbo",
        "tutor",
        "twirl",
        "worst",
      ],
      "npnpp": [
        "beret",
        "deter",
        "egret",
        "enter",
        "entry",
        "ester",
        "ether",
        "exert",
        "inert",
        "inter",
        "merit",
        "meter",
        "metro",
        "other",
        "otter",
        "outer",
        "overt",
        "rebut",
        "refit",
        "remit",
        "reset",
        "retro",
        "retry",
        "rivet",
        "steer",
        "stern",
        "tenor",
        "their",
        "threw",
        "tiger",
        "timer",
        "tower",
        "tuber",
        "utter",
        "voter",
      ],
      "nppen": [
        "aorta",
        "party",
        "ratty",
        "warty",
      ],
      "nppep": [
        "earth",
      ],
      "nppne": [
        "adore",
        "afire",
        "agree",
        "azure",
        "barge",
        "large",
        "parse",
        "raise",
        "range",
      ],
      "nppnn": [
        "abhor",
        "adorn",
        "agora",
        "angry",
        "apron",
        "augur",
        "baron",
        "borax",
        "dairy",
        "fairy",
        "favor",
        "flora",
        "foray",
        "hairy",
        "hardy",
        "harpy",
        "harry",
        "harsh",
        "karma",
        "labor",
        "larva",
        "lunar",
        "major",
        "manor",
        "marry",
        "marsh",
        "mayor",
        "molar",
        "moral",
        "mural",
        "nadir",
        "parka",
        "parry",
        "polar",
        "rabbi",
        "rabid",
        "radar",
        "radii",
        "radio",
        "rainy",
        "rajah",
        "rally",
        "ralph",
        "randy",
        "rapid",
        "raspy",
        "rayon",
        "razor",
        "rival",
        "royal",
        "rumba",
        "rural",
        "savor",
        "solar",
        "sonar",
        "spray",
        "sugar",
        "umbra",
        "valor",
        "vapor",
        "viral",
      ],
      "nppnp": [
        "aider",
        "amber",
        "anger",
        "baker",
        "baler",
        "debar",
        "eager",
        "early",
        "feral",
        "gamer",
        "gayer",
        "gazer",
        "harem",
        "lager",
        "layer",
        "maker",
        "opera",
        "paler",
        "paper",
        "parer",
        "payer",
        "ramen",
        "rarer",
        "raven",
        "rebar",
        "regal",
        "rehab",
        "relax",
        "relay",
        "renal",
        "repay",
        "safer",
        "saner",
        "shear",
        "smear",
        "spear",
        "swear",
        "wafer",
        "wager",
        "waver",
        "zebra",
      ],
      "npppn": [
        "abort",
        "altar",
        "ratio",
        "satyr",
        "strap",
        "straw",
        "stray",
        "tapir",
        "tardy",
        "tarot",
        "ultra",
      ],
      "npppp": [
        "after",
        "alert",
        "alter",
        "avert",
        "eater",
        "extra",
        "hater",
        "later",
        "taker",
        "tamer",
        "taper",
        "terra",
        "water",
      ],
      "peene": [
        "brace",
        "grace",
      ],
      "peenn": [
        "wrack",
      ],
      "peepe": [
        "trace",
      ],
      "peepn": [
        "track",
        "tract",
      ],
      "penne": [
        "price",
      ],
      "pennn": [
        "brick",
        "frock",
        "prick",
      ],
      "pennp": [
        "wreck",
      ],
      "penpe": [
        "trice",
        "truce",
      ],
      "penpn": [
        "trick",
        "truck",
      ],
      "penpp": [
        "erect",
      ],
      "pnene": [
        "peace",
        "place",
        "scale",
        "space",
      ],
      "pnenn": [
        "aback",
        "black",
        "flack",
        "knack",
        "quack",
        "scald",
        "scalp",
        "scaly",
        "scamp",
        "shack",
        "slack",
        "smack",
        "snack",
        "whack",
      ],
      "pnenp": [
        "beach",
        "leach",
        "peach",
      ],
      "pnepn": [
        "scant",
        "stack",
      ],
      "pnepp": [
        "enact",
        "exact",
        "teach",
      ],
      "pnnne": [
        "deuce",
        "dunce",
        "emcee",
        "fence",
        "hence",
        "juice",
        "mince",
        "niche",
        "niece",
        "ounce",
        "pence",
        "piece",
        "scene",
        "scone",
        "scope",
        "since",
        "slice",
        "spice",
        "uncle",
        "voice",
        "wince",
      ],
      "pnnnn": [
        "block",
        "bunch",
        "disco",
        "duchy",
        "ficus",
        "finch",
        "flick",
        "flock",
        "focus",
        "gulch",
        "hunch",
        "icily",
        "icing",
        "ionic",
        "juicy",
        "knock",
        "locus",
        "logic",
        "lucid",
        "lucky",
        "lunch",
        "lynch",
        "mimic",
        "mucky",
        "mucus",
        "mulch",
        "munch",
        "music",
        "picky",
        "pinch",
        "pluck",
        "pooch",
        "pouch",
        "pubic",
        "punch",
        "quick",
        "scion",
        "scoff",
        "scold",
        "scoop",
        "scowl",
        "shock",
        "shuck",
        "slick",
        "smock",
        "snuck",
        "sonic",
        "spicy",
        "vouch",
        "which",
        "winch",
      ],
      "pnnnp": [
        "beech",
        "belch",
        "bench",
        "bicep",
        "decoy",
        "dicey",
        "epoch",
        "excel",
        "fleck",
        "gecko",
        "leech",
        "medic",
        "speck",
        "welch",
        "wench",
      ],
      "pnnpe": [
        "twice",
      ],
      "pnnpn": [
        "botch",
        "butch",
        "ditch",
        "dutch",
        "hitch",
        "hutch",
        "itchy",
        "notch",
        "optic",
        "pitch",
        "scout",
        "stick",
        "stock",
        "stoic",
        "stuck",
        "thick",
        "tonic",
        "topic",
        "touch",
        "toxic",
        "tunic",
        "uncut",
        "witch",
      ],
      "pnnpp": [
        "edict",
        "eject",
        "elect",
        "ethic",
        "evict",
        "fetch",
        "octet",
        "scent",
      ],
      "pnpee": [
        "acute",
      ],
      "pnpne": [
        "dance",
        "lance",
        "sauce",
      ],
      "pnpnn": [
        "bacon",
        "basic",
        "fancy",
        "focal",
        "havoc",
        "iliac",
        "lilac",
        "local",
        "macaw",
        "macho",
        "magic",
        "manic",
        "mocha",
        "panic",
        "saucy",
        "scuba",
        "sumac",
        "vocal",
        "wacky",
      ],
      "pnpnp": [
        "decal",
        "decay",
        "fecal",
        "mecca",
        "ocean",
        "pecan",
      ],
      "pnppn": [
        "antic",
        "ascot",
        "attic",
        "batch",
        "hatch",
        "latch",
        "match",
        "octal",
        "patch",
        "tacit",
        "tacky",
        "watch",
        "yacht",
      ],
      "pnppp": [
        "eclat",
        "facet",
      ],
      "ppene": [
        "scare",
      ],
      "ppenn": [
        "roach",
        "scarf",
        "scary",
      ],
      "ppenp": [
        "reach",
      ],
      "ppepp": [
        "react",
      ],
      "ppnne": [
        "force",
        "score",
        "scree",
      ],
      "ppnnn": [
        "birch",
        "incur",
        "lurch",
        "lyric",
        "micro",
        "occur",
        "porch",
        "rocky",
        "scorn",
        "scour",
        "scrub",
        "scrum",
      ],
      "ppnnp": [
        "decor",
        "decry",
        "mercy",
        "nicer",
        "perch",
        "recur",
        "relic",
        "screw",
        "ulcer",
      ],
      "ppnpn": [
        "torch",
      ],
      "ppnpp": [
        "recut",
        "retch",
      ],
      "pppne": [
        "farce",
      ],
      "pppnn": [
        "acorn",
        "acrid",
        "macro",
        "march",
        "ranch",
        "scram",
        "scrap",
        "vicar",
      ],
      "pppnp": [
        "racer",
        "recap",
      ],
      "ppppn": [
        "actor",
      ],
    },
  };
  partitions = WordUtils.getWordlePartitions(words, picks);
  expect(partitions).toEqual(expected);
})

